#!/usr/bin/env bash
# ============================================================================
# CollectIQ one-command deploy — run this on your server (Hostinger VPS etc.):
#
#     bash deploy.sh
#
# It installs Docker if missing, creates the database automatically (a
# MongoDB container with persistent storage + daily backups), generates all
# security secrets, builds the app, and prints your admin login.
# Safe to re-run: an existing backend/.env is kept as-is.
# ============================================================================
set -euo pipefail
cd "$(dirname "$0")"

if ! command -v docker >/dev/null 2>&1; then
  echo ">> Docker not found — installing it now (one-time, ~1 min)..."
  curl -fsSL https://get.docker.com | sh
fi

ENV_FILE=backend/.env
GENERATED=0
if [ ! -f "$ENV_FILE" ]; then
  echo ">> Creating backend/.env with secure generated secrets..."
  JWT=$(head -c 64 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 48)
  ADMIN_EMAIL="${ADMIN_EMAIL:-admin@company.com}"
  ADMIN_PASSWORD="${ADMIN_PASSWORD:-$(head -c 32 /dev/urandom | base64 | tr -dc 'A-Za-z0-9' | head -c 16)}"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy.sh on $(date -u +%F). Keep this file private.
# The database URL below is overridden by docker-compose to the bundled
# MongoDB container; change it only if you move to MongoDB Atlas.
MONGO_URL=mongodb://mongo:27017
DB_NAME=collectiq
JWT_SECRET=$JWT
ADMIN_EMAIL=$ADMIN_EMAIL
ADMIN_PASSWORD=$ADMIN_PASSWORD
COOKIE_SECURE=${COOKIE_SECURE:-false}
COOKIE_SAMESITE=lax
EOF
  chmod 600 "$ENV_FILE"
  GENERATED=1
fi

echo ">> Building and starting CollectIQ (app + database + daily backups)..."
docker compose up -d --build

IP=$(hostname -I 2>/dev/null | awk '{print $1}')
echo ""
echo "=============================================================="
echo "  CollectIQ is up."
echo ""
echo "  Open:   http://${IP:-YOUR_SERVER_IP}:8080"
if [ "$GENERATED" = "1" ]; then
  echo ""
  echo "  Admin login — SAVE THIS SOMEWHERE SAFE NOW:"
  echo "     email:    ${ADMIN_EMAIL}"
  echo "     password: ${ADMIN_PASSWORD}"
  echo ""
  echo "  (You can change this password later from the Users page.)"
fi
echo ""
echo "  Database: runs automatically in a container. Your data"
echo "  persists across restarts, and a compressed backup is"
echo "  written to ./backups every 24h (last 14 kept)."
echo ""
echo "  To restore a backup:"
echo "     docker compose run --rm --entrypoint mongorestore backup \\"
echo "       --host mongo --gzip --drop --archive=/backups/<file>"
echo "=============================================================="
